FROM openjdk:17

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --assume-yes sshpass




sudo docker build -t myopenjdk:17 .



mvn jasypt:encrypt-value -Djasypt.encryptor.password="Hello@abc.com123" -Djasypt.plugin.value="root" -Djasypt.encryptor.algorithm="PBEWITHHMACSHA512ANDAES_256"
mvn jasypt:encrypt-value -Djasypt.encryptor.password="Hello@abc.com123" -Djasypt.plugin.value="123456" -Djasypt.encryptor.algorithm="PBEWITHHMACSHA512ANDAES_256"



mvn jasypt:encrypt-value -Djasypt.encryptor.password="Hello@abc.com123" -Djasypt.plugin.value="123456" -Djasypt.encryptor.algorithm="PBEWITHHMACSHA512ANDAES_256"


-----
加密：
mvn jasypt:encrypt-value -Djasypt.encryptor.password="Hello@abc.com123" -Djasypt.plugin.value="dbredis-ootkb0.serverless.apse1.cache.amazonaws.com" -Djasypt.encryptor.algorithm="PBEWITHHMACSHA512ANDAES_256"
解密：
mvn jasypt:decrypt-value -Djasypt.encryptor.password="Hello@abc.com123" -Djasypt.plugin.value="zIjkwsu6/RJRJ6QZEPp1xSkbVryU1L607P5wa9cJnnTKxAM16bYwYaAbVYIJu4wvp/kTzUJnKc/CCX9SsbiATg2jcw7xO1oYsG7c4KD68/qGAyKRAJ+fmWV8swwPqaT4ngcvA9EsSNsgR+0O8ypH5uMSRqBDeqkYMwVMk1T7WBGASlIFVgyjHVG5yCPGTbh7qTE6NRKcIekMAHPBR02f/nGr9vNWW8rX+3L4uoleeiYsSrd5Ql5d9Czh1mcR1RlowG45xeQ2dLGWnhWwE8sA7L1M9gpMNPbbdRRajXfByrWznHF92FMPIHIW+t1mx6X2" -Djasypt.encryptor.algorithm="PBEWITHHMACSHA512ANDAES_256"



-----


